# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

executors:
  linux_x64_executor: # declares a reusable executor
    docker:
      - image: secretflow/ubuntu-base-ci:latest
    resource_class: 2xlarge
    shell: /bin/bash --login -eo pipefail
  linux_aarch64_executor:
    docker:
      - image: secretflow/ubuntu-base-ci:latest
    resource_class: arm.2xlarge
    shell: /bin/bash --login -eo pipefail

commands:
  build_envoy:
    steps:
      - checkout
      - run:
          name: "make build-envoy-local"
          command: |
            git submodule update --init
            git config --global --add safe.directory ./
            bazel build //:envoy -c opt --ui_event_filters=-info,-debug,-warning --jobs 16
            mkdir -p build_apps/$(uname -m)
            mv bazel-bin/envoy build_apps/$(uname -m)
      - store_artifacts:
          path: build_apps

jobs:
  linux_build_envoy:
    parameters:
      executor:
        type: string
    executor: <<parameters.executor>>
    steps:
      - checkout
      - build_envoy
  docker_image_publish:
    docker:
      - image: cimg/deploy:2023.06.1
    steps:
      - attach_workspace:
          at: build_apps
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker buildx create --name kuscia-envoy --platform linux/arm64,linux/amd64 --use
            # login docker
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_DEPLOY_TOKEN}
            IMG=secretflow/kuscia-envoy:latest
            
            mkdir -p output/bin
            mv build_apps/aarch64/envoy output/bin
            docker buildx build -t ${IMG} --platform linux/arm64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push
            
            mv build_apps/x86_64/envoy output/bin
            docker buildx build -t ${IMG} --platform linux/amd64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push
            
            # login docker - aliyun
            docker login -u ${ALIYUN_DOCKER_USERNAME} -p ${ALIYUN_DOCKER_PASSWORD} secretflow-registry.cn-hangzhou.cr.aliyuncs.com
            
            mv build_apps/aarch64/envoy output/bin
            docker buildx build -t secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-envoy:latest --platform linux/arm64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push
            
            mv build_apps/x86_64/envoy output/bin
            docker buildx build -t secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-envoy:latest --platform linux/amd64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push
            


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - linux_publish:
          matrix:
            parameters:
              executor: [ "linux_x64_executor", "linux_aarch64_executor" ]
          filters:
            tags:
              only: /.*b[0-9]/
      - docker_image_publish:
          requires:
            - linux_publish
          filters:
            tags:
              only: /.*b[0-9]/