# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs

executors:
  linux_x64_executor: # declares a reusable executor
    docker:
      - image: secretflow/ubuntu-base-ci:latest
    resource_class: large
    shell: /bin/bash --login -eo pipefail
  linux_aarch64_executor:
    docker:
      - image: secretflow/ubuntu-base-ci:latest
    resource_class: arm.large
    shell: /bin/bash --login -eo pipefail

commands:
  build_envoy:
    steps:
      - run:
          name: "make build-envoy-local"
          command: |
            git submodule update --init
            git config --global --add safe.directory ./
            make build-envoy-local
      - store_artifacts:
          path: output

jobs:
  linux_build_envoy:
    parameters:
      executor:
        type: string
    executor: <<parameters.executor>>
    steps:
      - checkout
      - build_envoy
  docker_image_publish:
    docker:
      - image: cimg/deploy:2023.06.1
    steps:
      - attach_workspace:
          at: output
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker buildx create --name kuscia-envoy --platform linux/arm64,linux/amd64 --use
            IMG=secretflow/kuscia-envoy:latest
            
            #login docker
            docker login -u ${DOCKER_USERNAME} -p ${DOCKER_DEPLOY_TOKEN}
            
            docker buildx build -t ${IMG} --platform linux/arm64,linux/amd64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push
            
            
            # login docker - aliyun
            docker login -u ${ALIYUN_DOCKER_USERNAME} -p ${ALIYUN_DOCKER_PASSWORD} secretflow-registry.cn-hangzhou.cr.aliyuncs.com
            
            docker buildx build -t secretflow-registry.cn-hangzhou.cr.aliyuncs.com/secretflow/kuscia-envoy:latest --platform linux/amd64,linux/arm64 -f ./build_image/dockerfile/kuscia-envoy-anolis.Dockerfile . --push




# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - linux_build_envoy:
          matrix:
            parameters:
              executor: [ "linux_x64_executor", "linux_aarch64_executor" ]
      - docker_image_publish:
          requires:
            - linux_build_envoy
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/