# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-envoy:
    docker:
      - image: secretflow/ubuntu-base-ci:latest
    resource_class: large
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - run:
        name: Build envoy
        command: |
          git submodule update --init
          git config --global --add safe.directory ./
          bazel build //:envoy --verbose_failures
          mkdir -p build_apps
          mv bazel-bin/envoy build_apps
      - store_artifacts:
        path: build_apps

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-workflow:
    jobs:
      - build-envoy
