// Copyright 2024 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: poller.proto

package v3

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Poller struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReceiverServiceName string `protobuf:"bytes,1,opt,name=receiver_service_name,json=receiverServiceName,proto3" json:"receiver_service_name,omitempty"`
	RequestTimeout      int32  `protobuf:"varint,2,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	ResponseTimeout     int32  `protobuf:"varint,3,opt,name=response_timeout,json=responseTimeout,proto3" json:"response_timeout,omitempty"`
	// as a reverse proxy, header decorator filter append specified entries to the request headers.
	// for example, you can assign a token for each source, and the upstream cluster use the token to
	// authorize requests
	AppendHeaders []*Poller_SourceHeader `protobuf:"bytes,4,rep,name=append_headers,json=appendHeaders,proto3" json:"append_headers,omitempty"`
}

func (x *Poller) Reset() {
	*x = Poller{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poller_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poller) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poller) ProtoMessage() {}

func (x *Poller) ProtoReflect() protoreflect.Message {
	mi := &file_poller_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poller.ProtoReflect.Descriptor instead.
func (*Poller) Descriptor() ([]byte, []int) {
	return file_poller_proto_rawDescGZIP(), []int{0}
}

func (x *Poller) GetReceiverServiceName() string {
	if x != nil {
		return x.ReceiverServiceName
	}
	return ""
}

func (x *Poller) GetRequestTimeout() int32 {
	if x != nil {
		return x.RequestTimeout
	}
	return 0
}

func (x *Poller) GetResponseTimeout() int32 {
	if x != nil {
		return x.ResponseTimeout
	}
	return 0
}

func (x *Poller) GetAppendHeaders() []*Poller_SourceHeader {
	if x != nil {
		return x.AppendHeaders
	}
	return nil
}

type Poller_HeaderEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Poller_HeaderEntry) Reset() {
	*x = Poller_HeaderEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poller_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poller_HeaderEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poller_HeaderEntry) ProtoMessage() {}

func (x *Poller_HeaderEntry) ProtoReflect() protoreflect.Message {
	mi := &file_poller_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poller_HeaderEntry.ProtoReflect.Descriptor instead.
func (*Poller_HeaderEntry) Descriptor() ([]byte, []int) {
	return file_poller_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Poller_HeaderEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Poller_HeaderEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Poller_SourceHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source  string                `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Headers []*Poller_HeaderEntry `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
}

func (x *Poller_SourceHeader) Reset() {
	*x = Poller_SourceHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_poller_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Poller_SourceHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Poller_SourceHeader) ProtoMessage() {}

func (x *Poller_SourceHeader) ProtoReflect() protoreflect.Message {
	mi := &file_poller_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Poller_SourceHeader.ProtoReflect.Descriptor instead.
func (*Poller_SourceHeader) Descriptor() ([]byte, []int) {
	return file_poller_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Poller_SourceHeader) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Poller_SourceHeader) GetHeaders() []*Poller_HeaderEntry {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_poller_proto protoreflect.FileDescriptor

var file_poller_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2e,
	0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6b, 0x75,
	0x73, 0x63, 0x69, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x22, 0xba,
	0x03, 0x0a, 0x06, 0x50, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x32, 0x0a, 0x15, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x0a,
	0x0f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54,
	0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x12, 0x6a, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x5f, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x43, 0x2e, 0x65, 0x6e, 0x76, 0x6f,
	0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61,
	0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e, 0x50, 0x6f, 0x6c, 0x6c, 0x65,
	0x72, 0x2e, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0d,
	0x61, 0x70, 0x70, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x1a, 0x35, 0x0a,
	0x0b, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x84, 0x01, 0x0a, 0x0c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x5c, 0x0a,
	0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x42,
	0x2e, 0x65, 0x6e, 0x76, 0x6f, 0x79, 0x2e, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x6b,
	0x75, 0x73, 0x63, 0x69, 0x61, 0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x76, 0x33, 0x2e,
	0x50, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x42, 0x4d, 0x5a, 0x4b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74,
	0x66, 0x6c, 0x6f, 0x77, 0x2f, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2d, 0x65, 0x6e, 0x76, 0x6f,
	0x79, 0x2f, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x73, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x6b, 0x75, 0x73, 0x63, 0x69, 0x61,
	0x5f, 0x70, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2f, 0x76, 0x33, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_poller_proto_rawDescOnce sync.Once
	file_poller_proto_rawDescData = file_poller_proto_rawDesc
)

func file_poller_proto_rawDescGZIP() []byte {
	file_poller_proto_rawDescOnce.Do(func() {
		file_poller_proto_rawDescData = protoimpl.X.CompressGZIP(file_poller_proto_rawDescData)
	})
	return file_poller_proto_rawDescData
}

var file_poller_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_poller_proto_goTypes = []interface{}{
	(*Poller)(nil),              // 0: envoy.extensions.filters.http.kuscia_poller.v3.Poller
	(*Poller_HeaderEntry)(nil),  // 1: envoy.extensions.filters.http.kuscia_poller.v3.Poller.HeaderEntry
	(*Poller_SourceHeader)(nil), // 2: envoy.extensions.filters.http.kuscia_poller.v3.Poller.SourceHeader
}
var file_poller_proto_depIdxs = []int32{
	2, // 0: envoy.extensions.filters.http.kuscia_poller.v3.Poller.append_headers:type_name -> envoy.extensions.filters.http.kuscia_poller.v3.Poller.SourceHeader
	1, // 1: envoy.extensions.filters.http.kuscia_poller.v3.Poller.SourceHeader.headers:type_name -> envoy.extensions.filters.http.kuscia_poller.v3.Poller.HeaderEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_poller_proto_init() }
func file_poller_proto_init() {
	if File_poller_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_poller_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poller); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poller_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poller_HeaderEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_poller_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Poller_SourceHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_poller_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_poller_proto_goTypes,
		DependencyIndexes: file_poller_proto_depIdxs,
		MessageInfos:      file_poller_proto_msgTypes,
	}.Build()
	File_poller_proto = out.File
	file_poller_proto_rawDesc = nil
	file_poller_proto_goTypes = nil
	file_poller_proto_depIdxs = nil
}
