// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: poller.proto

package v3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Poller with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Poller) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Poller with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in PollerMultiError, or nil if none found.
func (m *Poller) ValidateAll() error {
	return m.validate(true)
}

func (m *Poller) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ReceiverServiceName

	// no validation rules for RequestTimeout

	// no validation rules for ResponseTimeout

	for idx, item := range m.GetAppendHeaders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PollerValidationError{
						field:  fmt.Sprintf("AppendHeaders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PollerValidationError{
						field:  fmt.Sprintf("AppendHeaders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PollerValidationError{
					field:  fmt.Sprintf("AppendHeaders[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return PollerMultiError(errors)
	}

	return nil
}

// PollerMultiError is an error wrapping multiple validation errors returned by
// Poller.ValidateAll() if the designated constraints aren't met.
type PollerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PollerMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PollerMultiError) AllErrors() []error { return m }

// PollerValidationError is the validation error returned by Poller.Validate if
// the designated constraints aren't met.
type PollerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PollerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PollerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PollerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PollerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PollerValidationError) ErrorName() string { return "PollerValidationError" }

// Error satisfies the builtin error interface
func (e PollerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPoller.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PollerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PollerValidationError{}

// Validate checks the field values on Poller_HeaderEntry with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Poller_HeaderEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Poller_HeaderEntry with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Poller_HeaderEntryMultiError, or nil if none found.
func (m *Poller_HeaderEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *Poller_HeaderEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	if len(errors) > 0 {
		return Poller_HeaderEntryMultiError(errors)
	}

	return nil
}

// Poller_HeaderEntryMultiError is an error wrapping multiple validation errors
// returned by Poller_HeaderEntry.ValidateAll() if the designated constraints
// aren't met.
type Poller_HeaderEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Poller_HeaderEntryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Poller_HeaderEntryMultiError) AllErrors() []error { return m }

// Poller_HeaderEntryValidationError is the validation error returned by
// Poller_HeaderEntry.Validate if the designated constraints aren't met.
type Poller_HeaderEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Poller_HeaderEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Poller_HeaderEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Poller_HeaderEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Poller_HeaderEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Poller_HeaderEntryValidationError) ErrorName() string {
	return "Poller_HeaderEntryValidationError"
}

// Error satisfies the builtin error interface
func (e Poller_HeaderEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPoller_HeaderEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Poller_HeaderEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Poller_HeaderEntryValidationError{}

// Validate checks the field values on Poller_SourceHeader with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *Poller_SourceHeader) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Poller_SourceHeader with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Poller_SourceHeaderMultiError, or nil if none found.
func (m *Poller_SourceHeader) ValidateAll() error {
	return m.validate(true)
}

func (m *Poller_SourceHeader) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Source

	for idx, item := range m.GetHeaders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, Poller_SourceHeaderValidationError{
						field:  fmt.Sprintf("Headers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, Poller_SourceHeaderValidationError{
						field:  fmt.Sprintf("Headers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return Poller_SourceHeaderValidationError{
					field:  fmt.Sprintf("Headers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return Poller_SourceHeaderMultiError(errors)
	}

	return nil
}

// Poller_SourceHeaderMultiError is an error wrapping multiple validation
// errors returned by Poller_SourceHeader.ValidateAll() if the designated
// constraints aren't met.
type Poller_SourceHeaderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Poller_SourceHeaderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Poller_SourceHeaderMultiError) AllErrors() []error { return m }

// Poller_SourceHeaderValidationError is the validation error returned by
// Poller_SourceHeader.Validate if the designated constraints aren't met.
type Poller_SourceHeaderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Poller_SourceHeaderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Poller_SourceHeaderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Poller_SourceHeaderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Poller_SourceHeaderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Poller_SourceHeaderValidationError) ErrorName() string {
	return "Poller_SourceHeaderValidationError"
}

// Error satisfies the builtin error interface
func (e Poller_SourceHeaderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPoller_SourceHeader.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Poller_SourceHeaderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Poller_SourceHeaderValidationError{}
