// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kuscia/api/filters/http/kuscia_token_auth/v3/token_auth.proto

package v3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TokenAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TokenAuth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenAuth with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TokenAuthMultiError, or nil
// if none found.
func (m *TokenAuth) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenAuth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetSourceTokenList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, TokenAuthValidationError{
						field:  fmt.Sprintf("SourceTokenList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, TokenAuthValidationError{
						field:  fmt.Sprintf("SourceTokenList[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return TokenAuthValidationError{
					field:  fmt.Sprintf("SourceTokenList[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return TokenAuthMultiError(errors)
	}

	return nil
}

// TokenAuthMultiError is an error wrapping multiple validation errors returned
// by TokenAuth.ValidateAll() if the designated constraints aren't met.
type TokenAuthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenAuthMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenAuthMultiError) AllErrors() []error { return m }

// TokenAuthValidationError is the validation error returned by
// TokenAuth.Validate if the designated constraints aren't met.
type TokenAuthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenAuthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenAuthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenAuthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenAuthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenAuthValidationError) ErrorName() string { return "TokenAuthValidationError" }

// Error satisfies the builtin error interface
func (e TokenAuthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenAuth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenAuthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenAuthValidationError{}

// Validate checks the field values on FilterConfigPerRoute with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *FilterConfigPerRoute) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on FilterConfigPerRoute with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// FilterConfigPerRouteMultiError, or nil if none found.
func (m *FilterConfigPerRoute) ValidateAll() error {
	return m.validate(true)
}

func (m *FilterConfigPerRoute) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Disabled

	if len(errors) > 0 {
		return FilterConfigPerRouteMultiError(errors)
	}

	return nil
}

// FilterConfigPerRouteMultiError is an error wrapping multiple validation
// errors returned by FilterConfigPerRoute.ValidateAll() if the designated
// constraints aren't met.
type FilterConfigPerRouteMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m FilterConfigPerRouteMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m FilterConfigPerRouteMultiError) AllErrors() []error { return m }

// FilterConfigPerRouteValidationError is the validation error returned by
// FilterConfigPerRoute.Validate if the designated constraints aren't met.
type FilterConfigPerRouteValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e FilterConfigPerRouteValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e FilterConfigPerRouteValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e FilterConfigPerRouteValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e FilterConfigPerRouteValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e FilterConfigPerRouteValidationError) ErrorName() string {
	return "FilterConfigPerRouteValidationError"
}

// Error satisfies the builtin error interface
func (e FilterConfigPerRouteValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sFilterConfigPerRoute.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = FilterConfigPerRouteValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = FilterConfigPerRouteValidationError{}

// Validate checks the field values on TokenAuth_SourceToken with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TokenAuth_SourceToken) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenAuth_SourceToken with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TokenAuth_SourceTokenMultiError, or nil if none found.
func (m *TokenAuth_SourceToken) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenAuth_SourceToken) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Source

	if len(errors) > 0 {
		return TokenAuth_SourceTokenMultiError(errors)
	}

	return nil
}

// TokenAuth_SourceTokenMultiError is an error wrapping multiple validation
// errors returned by TokenAuth_SourceToken.ValidateAll() if the designated
// constraints aren't met.
type TokenAuth_SourceTokenMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenAuth_SourceTokenMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenAuth_SourceTokenMultiError) AllErrors() []error { return m }

// TokenAuth_SourceTokenValidationError is the validation error returned by
// TokenAuth_SourceToken.Validate if the designated constraints aren't met.
type TokenAuth_SourceTokenValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenAuth_SourceTokenValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenAuth_SourceTokenValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenAuth_SourceTokenValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenAuth_SourceTokenValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenAuth_SourceTokenValidationError) ErrorName() string {
	return "TokenAuth_SourceTokenValidationError"
}

// Error satisfies the builtin error interface
func (e TokenAuth_SourceTokenValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenAuth_SourceToken.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenAuth_SourceTokenValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenAuth_SourceTokenValidationError{}
