// Copyright 2023 Ant Group Co., Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: kuscia/api/filters/http/kuscia_header_decorator/v3/header_decorator.proto

package v3

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on HeaderDecorator with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HeaderDecorator) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeaderDecorator with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeaderDecoratorMultiError, or nil if none found.
func (m *HeaderDecorator) ValidateAll() error {
	return m.validate(true)
}

func (m *HeaderDecorator) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAppendHeaders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HeaderDecoratorValidationError{
						field:  fmt.Sprintf("AppendHeaders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HeaderDecoratorValidationError{
						field:  fmt.Sprintf("AppendHeaders[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HeaderDecoratorValidationError{
					field:  fmt.Sprintf("AppendHeaders[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HeaderDecoratorMultiError(errors)
	}

	return nil
}

// HeaderDecoratorMultiError is an error wrapping multiple validation errors
// returned by HeaderDecorator.ValidateAll() if the designated constraints
// aren't met.
type HeaderDecoratorMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeaderDecoratorMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeaderDecoratorMultiError) AllErrors() []error { return m }

// HeaderDecoratorValidationError is the validation error returned by
// HeaderDecorator.Validate if the designated constraints aren't met.
type HeaderDecoratorValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeaderDecoratorValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeaderDecoratorValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeaderDecoratorValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeaderDecoratorValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeaderDecoratorValidationError) ErrorName() string { return "HeaderDecoratorValidationError" }

// Error satisfies the builtin error interface
func (e HeaderDecoratorValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeaderDecorator.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeaderDecoratorValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeaderDecoratorValidationError{}

// Validate checks the field values on HeaderDecorator_HeaderEntry with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HeaderDecorator_HeaderEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeaderDecorator_HeaderEntry with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeaderDecorator_HeaderEntryMultiError, or nil if none found.
func (m *HeaderDecorator_HeaderEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *HeaderDecorator_HeaderEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	// no validation rules for Value

	if len(errors) > 0 {
		return HeaderDecorator_HeaderEntryMultiError(errors)
	}

	return nil
}

// HeaderDecorator_HeaderEntryMultiError is an error wrapping multiple
// validation errors returned by HeaderDecorator_HeaderEntry.ValidateAll() if
// the designated constraints aren't met.
type HeaderDecorator_HeaderEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeaderDecorator_HeaderEntryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeaderDecorator_HeaderEntryMultiError) AllErrors() []error { return m }

// HeaderDecorator_HeaderEntryValidationError is the validation error returned
// by HeaderDecorator_HeaderEntry.Validate if the designated constraints
// aren't met.
type HeaderDecorator_HeaderEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeaderDecorator_HeaderEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeaderDecorator_HeaderEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeaderDecorator_HeaderEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeaderDecorator_HeaderEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeaderDecorator_HeaderEntryValidationError) ErrorName() string {
	return "HeaderDecorator_HeaderEntryValidationError"
}

// Error satisfies the builtin error interface
func (e HeaderDecorator_HeaderEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeaderDecorator_HeaderEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeaderDecorator_HeaderEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeaderDecorator_HeaderEntryValidationError{}

// Validate checks the field values on HeaderDecorator_SourceHeader with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *HeaderDecorator_SourceHeader) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeaderDecorator_SourceHeader with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeaderDecorator_SourceHeaderMultiError, or nil if none found.
func (m *HeaderDecorator_SourceHeader) ValidateAll() error {
	return m.validate(true)
}

func (m *HeaderDecorator_SourceHeader) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Source

	for idx, item := range m.GetHeaders() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, HeaderDecorator_SourceHeaderValidationError{
						field:  fmt.Sprintf("Headers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, HeaderDecorator_SourceHeaderValidationError{
						field:  fmt.Sprintf("Headers[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return HeaderDecorator_SourceHeaderValidationError{
					field:  fmt.Sprintf("Headers[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return HeaderDecorator_SourceHeaderMultiError(errors)
	}

	return nil
}

// HeaderDecorator_SourceHeaderMultiError is an error wrapping multiple
// validation errors returned by HeaderDecorator_SourceHeader.ValidateAll() if
// the designated constraints aren't met.
type HeaderDecorator_SourceHeaderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeaderDecorator_SourceHeaderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeaderDecorator_SourceHeaderMultiError) AllErrors() []error { return m }

// HeaderDecorator_SourceHeaderValidationError is the validation error returned
// by HeaderDecorator_SourceHeader.Validate if the designated constraints
// aren't met.
type HeaderDecorator_SourceHeaderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeaderDecorator_SourceHeaderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeaderDecorator_SourceHeaderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeaderDecorator_SourceHeaderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeaderDecorator_SourceHeaderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeaderDecorator_SourceHeaderValidationError) ErrorName() string {
	return "HeaderDecorator_SourceHeaderValidationError"
}

// Error satisfies the builtin error interface
func (e HeaderDecorator_SourceHeaderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeaderDecorator_SourceHeader.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeaderDecorator_SourceHeaderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeaderDecorator_SourceHeaderValidationError{}
